---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: federated-prometheus-for-pcf

outputs:
- name: dynamic-params

params:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:

run:
  path: federated-prometheus-for-pcf/pipeline-agent/tasks/retrieve-params-from-opsman.sh
