# BOSH deployment name
deployment: prometheus-master

# Federated agents
federated_agents: []

# This will be the admin password to log in to Grafana GUI
grafana_admin_password: 
# This will be the admin password to log in to Prometheus GUI
prometheus_admin_password: 
# This will be the admin password to log in to Alertmanager GUI
alertmanager_admin_password: 

# Below configure where and how to deploy the "Master" Prometheus
# BOSH Director to deploy to, e.g. https://10.0.0.10:25555
deploy_bosh_target: 
deploy_bosh_admin: 
deploy_bosh_admin_secret: 
# BOSH Director ca cert, one may get it by `bosh int creds.yml --path /director_ssl/ca`
deploy_bosh_ca_cert: 
# AZ(s) to deploy to (as defined in the Director cloud config)
deploy_azs: [z1]
# network to deploy to (as defined in the Director cloud config); one may also set the static IP here to expose out
deploy_network: [{name: default}]
# VM type for the components
deploy_vm_type_prometheus: 
deploy_vm_type_alertmanager: 
deploy_vm_type_database: 
deploy_vm_type_grafana: 
deploy_vm_type_nginx: 
# persistent disk type
deploy_persistent_disk_prometheus: 10_000
deploy_persistent_disk_database: 10_000

# Whether to skip SSL validation
skip_ssl_verify: true

# Github token to authenticate with Github. You can generate one at https://github.com/settings/tokens
github_token: 
