resource_types:
- name: bosh-deploy
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: federated-prometheus-for-pcf
  type: git
  source:
    uri: https://github.com/brightzheng100/federated-prometheus-for-pcf.git
    branch: master
- name: prometheus-release-git
  type: git
  source:
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease.git
    branch: master
    tag_filter: "v22?0*"        #v22.0.x
- name: prometheus-release-blob
  type: github-release
  source:
    user: bosh-prometheus
    repository: prometheus-boshrelease
    tag_filter: "v22?0*"        #v22.0.x
    access_token: ((github_token))
- name: bosh-deployment
  type: bosh-deploy
  source:
    deployment: ((deployment))
    target: ((deploy_bosh_target))
    client: ((deploy_bosh_admin))
    client_secret: ((deploy_bosh_admin_secret))
    ca_cert: ((deploy_bosh_ca_cert))

jobs:
- name: deploy
  plan:
  - get: federated-prometheus-for-pcf
  - get: prometheus-release-git
  - get: prometheus-release-blob
  - put: bosh-deployment
    params:
      manifest: prometheus-release-git/manifests/prometheus.yml
      releases:
      - prometheus-release-blob/prometheus-*.tgz
      ops_files:
      - federated-prometheus-for-pcf/ops-files/prometheus-master-job.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-federation.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-dashboards-bosh.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-dashboards-cf.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-dashboards-node.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-scrape-bosh.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-scrape-cf.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-scrape-firehose.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-master-scrape-node.yml
      vars:
        deployment: ((deployment))
        azs: ((deploy_azs))
        network: ((deploy_network))
        vm_type_prometheus: ((deploy_vm_type_prometheus))
        vm_type_alertmanager: ((deploy_vm_type_alertmanager))
        vm_type_database: ((deploy_vm_type_database))
        vm_type_grafana: ((deploy_vm_type_grafana))
        vm_type_nginx: ((deploy_vm_type_nginx))
        persistent_disk_prometheus: ((deploy_persistent_disk_prometheus))
        persistent_disk_database: ((deploy_persistent_disk_database))
        skip_ssl_verify: ((skip_ssl_verify))
        grafana_password: ((grafana_admin_password))
        prometheus_password: ((prometheus_admin_password))
        alertmanager_password: ((alertmanager_admin_password))
        federated_agents: ((federated_agents))

- name: destroy
  plan:
  - put: bosh-deployment
    params:
      delete:
        enabled: true
        force: true
