---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: federated-prometheus-for-pcf
- name: pcf-bosh-creds

params:
  deployment:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  director_to_monitor:

run:
  path: federated-prometheus-for-pcf/pipeline-agent/tasks/delete-prometheus.sh
