
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs
  value:
  - job_name: 'federate'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /federate
    scheme: http
    params:
      'match[]':
        - '{job="bosh"}'
        - '{job="cf_exporter"}'
        - '{job="firehose_exporter"}'
        - '{job="node"}'
    static_configs:
    - targets: ((federated_agents))

# global:
#     external_labels:
#       foundation: non-prod

