# BOSH deployment name
deployment: prometheus-agent

# Operations Manager credentials to set
pcf_opsman_admin_username: 
pcf_opsman_admin_password: 
opsman_url: 

# Set to either opsman_bosh or external_bosh that one is going to monitor by deploying bosh_exporter
# For external BOSH you need to provide the details below
director_to_monitor: opsman_bosh
# If you set director_to_monitor to external_bosh then you need to provide the Director details; 
# otherwise keep them empty as BOSH info will be retrieved back automatically by scripts
external_bosh_address:
external_bosh_client:
external_bosh_client_secret:
external_bosh_ca_cert:

# set to something very secure! you won't need to use these passwords at all
# or simply let CredHub to generate it and refer it by using ((xxx))
uaa_client_firehose_exporter_secret: 
uaa_client_cf_exporter_secret: 
uaa_client_bosh_exporter_secret: 

# Below configure where and how to deploy the "Agent" itself
# BOSH Director to deploy to, e.g. https://10.0.0.10:25555
deploy_bosh_target: 
deploy_bosh_admin: 
deploy_bosh_admin_secret: 
# BOSH Director ca cert, one may get it by `bosh int creds.yml --path /director_ssl/ca`
deploy_bosh_ca_cert: 
# AZ(s) to deploy to (as defined in the Director cloud config)
deploy_azs: [z1]
# network to deploy to (as defined in the Director cloud config); one may also set the static IP here to expose out
deploy_network: [{name: default}]
# VM type for this "Agent" node
deploy_vm_type: 
# persistent disk
deploy_persistent_disk: 10_000

# Whether to skip SSL validation
skip_ssl_verify: true

# arbitrary name for this environment (eg. 'prod')
metrics_environment: pcf

# Github token to authenticate with Github. You can generate one at https://github.com/settings/tokens
github_token: 
