resource_types:
- name: bosh-creds
  type: docker-image
  source:
    repository: mkuratczyk/bosh-creds-resource
    tag: 1.3
- name: bosh-deploy
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: federated-prometheus-for-pcf
  type: git
  source:
    uri: https://github.com/brightzheng100/federated-prometheus-for-pcf.git
    branch: master
- name: prometheus-release-git
  type: git
  source:
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease.git
    branch: master
    tag_filter: "v22?0*"        #v22.0.x
- name: prometheus-release-blob
  type: github-release
  source:
    user: bosh-prometheus
    repository: prometheus-boshrelease
    access_token: ((github_token))
- name: node-exporter-release
  type: github-release
  source:
    user: bosh-prometheus
    repository: node-exporter-boshrelease
    tag_filter: "v22?0*"        #v22.0.x
    access_token: ((github_token))
- name: pcf-bosh-creds
  type: bosh-creds
  source:
    pcf_opsman_admin_username: ((pcf_opsman_admin_username))
    pcf_opsman_admin_password: ((pcf_opsman_admin_password))
    opsman_url: ((opsman_url))
    external_bosh_address: ((external_bosh_address))
    external_bosh_client: ((external_bosh_client))
    external_bosh_client_secret: ((external_bosh_client_secret))
    external_bosh_ca_cert: ((external_bosh_ca_cert))
- name: bosh-deployment
  type: bosh-deploy
  source:
    deployment: ((deployment))
    target: ((deploy_bosh_target))
    client: ((deploy_bosh_admin))
    client_secret: ((deploy_bosh_admin_secret))
    ca_cert: ((deploy_bosh_ca_cert))

jobs:
- name: create-uaa-clients
  plan:
  - get: federated-prometheus-for-pcf
  - task: create-uaa-clients
    file: federated-prometheus-for-pcf/pipeline-agent/tasks/create-uaa-clients.yml
    params:
      opsman_url: ((opsman_url))
      pcf_opsman_admin_username: ((pcf_opsman_admin_username))
      pcf_opsman_admin_password: ((pcf_opsman_admin_password))
      uaa_client_firehose_exporter_secret: ((uaa_client_firehose_exporter_secret))
      uaa_client_cf_exporter_secret: ((uaa_client_cf_exporter_secret))
      uaa_client_bosh_exporter_secret: ((uaa_client_bosh_exporter_secret))

- name: install-node-exporter
  plan:
  - aggregate:
    - get: node-exporter-release
    - get: federated-prometheus-for-pcf
      passed: [create-uaa-clients]
    - get: pcf-bosh-creds
  - task: install-node-exporter
    file: federated-prometheus-for-pcf/pipeline-agent/tasks/install-node-exporter.yml

- name: deploy
  plan:
  - get: federated-prometheus-for-pcf
    passed: [install-node-exporter]
  - get: prometheus-release-git
  - get: prometheus-release-blob
  - get: pcf-bosh-creds
    params:
      deployment: ((deployment))
  - task: retrieve-params-from-opsman
    file: federated-prometheus-for-pcf/pipeline-agent/tasks/retrieve-params-from-opsman.yml
    params:
      pcf_opsman_admin_username: ((pcf_opsman_admin_username))
      pcf_opsman_admin_password: ((pcf_opsman_admin_password))
      opsman_url: ((opsman_url))
  - put: bosh-deployment
    params:
      manifest: prometheus-release-git/manifests/prometheus.yml
      releases:
      - prometheus-release-blob/prometheus-*.tgz
      ops_files:
      - prometheus-release-git/manifests/operators/monitor-bosh.yml
      - prometheus-release-git/manifests/operators/enable-bosh-uaa.yml
      - prometheus-release-git/manifests/operators/monitor-cf.yml
      - prometheus-release-git/manifests/operators/monitor-node.yml
      - federated-prometheus-for-pcf/ops-files/prometheus-agent-job.yml
      - federated-prometheus-for-pcf/ops-files/remove-alertmanager.yml
      - federated-prometheus-for-pcf/ops-files/remove-grafana.yml
      - federated-prometheus-for-pcf/ops-files/remove-nginx.yml
      - federated-prometheus-for-pcf/ops-files/colocate-postgres.yml
      - federated-prometheus-for-pcf/ops-files/colocate-firehose-exporter.yml
      - federated-prometheus-for-pcf/ops-files/local-cf-exporter.yml
      vars:
        deployment: ((deployment))
        azs: ((deploy_azs))
        network: ((deploy_network))
        vm_type: ((deploy_vm_type))
        persistent_disk: ((deploy_persistent_disk))
        metrics_environment: ((metrics_environment))
        uaa_client_firehose_exporter_secret: ((uaa_client_firehose_exporter_secret))
        uaa_clients_cf_exporter_secret: ((uaa_client_cf_exporter_secret))
        uaa_bosh_exporter_client_secret: ((uaa_client_bosh_exporter_secret))
        skip_ssl_verify: ((skip_ssl_verify))
      vars_files:
        - pcf-bosh-creds/pcf_bosh_director.yml
        - dynamic-params/params.yml

- name: destroy
  plan:
  - get: federated-prometheus-for-pcf
  #- get: pcf-bosh-creds
  - task: delete-uaa-clients
    file: federated-prometheus-for-pcf/pipeline-agent/tasks/delete-uaa-clients.yml
    params:
      deployment: ((deployment))
      opsman_url: ((opsman_url))
      pcf_opsman_admin_username: ((pcf_opsman_admin_username))
      pcf_opsman_admin_password: ((pcf_opsman_admin_password))
      director_to_monitor: ((director_to_monitor))
  - put: bosh-deployment
    params:
      delete:
        enabled: true
        force: true
